name: roof
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python版本
  - python=3.10.18
  
  # 核心深度学习框架
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8  # 或12.1，根据您的CUDA版本
  
  # 科学计算基础
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  
  # 图像处理
  - opencv>=4.8.0
  - pillow>=10.0.0
  - imageio>=2.31.0
  
  # 可视化
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Jupyter环境
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - ipywidgets>=8.0.0
  - jupyterlab>=4.0.0
  
  # 机器学习
  - scikit-learn>=1.3.0
  
  # 配置和工具
  - pyyaml>=6.0.0
  - tqdm>=4.65.0
  - requests>=2.31.0
  - click>=8.1.0
  
  # 开发工具
  - black>=23.0.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - pytest>=7.4.0
  
  # pip安装的包
  - pip
  - pip:
    # 专家改进版核心
    - ultralytics==8.3.3
    - roboflow>=1.1.0
    
    # 图像增强
    - albumentations>=1.3.0
    - imgaug>=0.4.0
    
    # 配置管理
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    
    # 监控和可视化
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    - rich>=13.0.0
    
    # 测试
    - pytest-cov>=4.1.0
    
    # Python 3.10兼容性
    - typing-extensions>=4.7.0
    - importlib-metadata>=6.8.0
